language: java

jdk:
  - oraclejdk8



addons:
  sonarcloud:
    organization: " tangkunprimeledger-github" # the key of the org you chose at step #3
    token:
      secure: 5d42885da3e2789bcd6075b635b6432d909b5898 # encrypted value of your token
script: mvn package -DskipTests=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
# script:
 #- mvn test -DskipTests=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true


after_success:
  - mvn jacoco:report  sonar:sonar  
  

  
  

